---
ci:
  skip:
    - ansible-lint
    - deps
    - lock
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    # keep it before yamllint
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        # Temporary excludes so we can gradually normalize the formatting
        exclude: >
          (?x)^(
            test/resources/templates/.*|
          )$
        additional_dependencies:
          - prettier
          - prettier-plugin-toml

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
        language_version: python3

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.4.8"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.8.2
    hooks:
      - id: cspell
        name: Spell check with cspell

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: flake8(pydoclint)
        additional_dependencies:
          - pydoclint[flake8]

  - repo: https://github.com/pre-commit/mirrors-mypy.git
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies:
          - ansible-compat>=24.6.1
          - click
          - click-help-colors
          - enrich
          - pytest
          - pytest-mock
          - rich
          - types-pyyaml
          - types-filelock
          - types-jsonschema
          - types-pexpect
          - types-setuptools
          - wcmatch
        # Override default pre-commit '--ignore-missing-imports'
        args: [--strict]

  - repo: https://github.com/pycqa/pylint.git
    rev: v3.2.3
    hooks:
      - id: pylint
        args:
          - --output-format=colorized
        additional_dependencies:
          - ansible-compat>=24.6.1
          - click
          - click-help-colors
          - enrich>=1.2.7
          - filelock
          - jsonschema
          - pexpect
          - pytest-mock
          - pytest-testinfra
          - wcmatch

  - repo: https://github.com/ansible/ansible-lint
    rev: v24.6.0
    hooks:
      - id: ansible-lint
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.4.1
    hooks:
      - id: pip-compile
        name: lock
        alias: lock
        always_run: true
        entry: pip-compile --upgrade --no-annotate --output-file=.config/constraints.txt pyproject.toml --all-extras --strip-extras --unsafe-package wcmatch --unsafe-package ruamel-yaml-clib --unsafe-package resolvelib
        files: ^.config\/.*requirements.*$
        language: python
        language_version: "3.10" # minimal we support officially
        pass_filenames: false
        stages: [manual]
        additional_dependencies:
          - pip>=22.3.1
      - id: pip-compile
        name: deps
        alias: deps
        always_run: true
        entry: pip-compile --no-annotate --output-file=.config/constraints.txt pyproject.toml --all-extras --strip-extras --unsafe-package wcmatch --unsafe-package ruamel-yaml-clib --unsafe-package resolvelib
        files: ^.config\/.*requirements.*$
        language: python
        language_version: "3.10" # minimal we support officially
        pass_filenames: false
        additional_dependencies:
          - pip>=22.3.1
