---
site_name: Ansible Molecule
site_url: https://ansible.readthedocs.io/projects/molecule/
repo_url: https://github.com/ansible-community/molecule
edit_uri: blob/main/docs/
copyright: Copyright Â© 2023 Red Hat, Inc.
strict: true

theme:
  name: ansible
  features:
    - content.code.copy
    - content.action.edit
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - toc.integrate
extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/molecule/
      name: PyPI
    - icon: fontawesome/solid/scroll
      link: https://github.com/ansible-community/molecule/releases
      name: Releases
    - icon: simple/matrix
      link: https://matrix.to/#/#devtools:ansible.com
      name: Matrix
    - icon: fontawesome/solid/comments
      link: https://github.com/ansible-community/molecule/discussions
      name: Discussions
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ansible-community/molecule

nav:
  - Home: index.md
  - installation.md
  - Using:
      - getting-started.md
      - usage.md
      - next.md
      - configuration.md
      - ci.md
  - Examples:
      - docker.md
      - podman.md
      - kubevirt.md
  - examples.md
  - faq.md
  - contributing.md
  - Future documentation (WIP):
      - Introduction: working/introduction/introduction.md
      - Installation:
          - working/installation/install.md
          - working/installation/upgrade.md
      - Getting Started: working/getting_started/getting_started.md
      - User Guide:
          - working/user_guide/understanding.md
          - working/user_guide/creating_testing_collection.md
          - working/user_guide/testing_existing_collection.md
          - working/user_guide/testing_existing_roles.md
          - working/user_guide/ci_integration.md
          - working/user_guide/using_tox-ansible.md
      - References:
          - working/references/cli.md
          - working/references/configuration.md
          - working/references/porting_change_log.md
          - working/references/road_map.md
      - Examples:
          - working/examples/example_1.md
          - working/examples/example_2.md
          - working/examples/example_3.md
      - Frequently asked questions: working/faq/faq.md
      - Contributor Guide:
          - working/contributor_guide/code_of_conduct.md
          - working/contributor_guide/developer_contact.md
          - working/contributor_guide/environment_setup.md
          - working/contributor_guide/contribution_requirements.md

plugins:
  - autorefs
  - search
  - material/social

  - mkdocstrings:
      enable_inventory: true
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            # Sphinx is for historical reasons, but we could consider switching if needed
            # https://mkdocstrings.github.io/griffe/docstrings/
            docstring_style: sphinx
            merge_init_into_class: yes
            show_submodules: yes
          import:
            - url: https://docs.ansible.com/ansible/latest/objects.inv
              domains: [py, std, "std:doc", "std:label"]
            - url: https://pip.pypa.io/en/latest/objects.inv
              domains: [py, std]

markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - admonition
  - def_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      normalize_issue_symbols: true
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      # reduced to keep TOC nice under Changelog page
      toc_depth: 2
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
