---
- name: Create VM dictionary
  vars:
    # This variable block is setting the `ssh_service_address` variable.
    # It first checks if the service type of the SSH service is 'NodePort'.
    # If it is, it retrieves the 'nodePort' from the services results.
    ssh_service_address: >-
      {%- set svc_type = vm.ssh_service.type | default(None) -%}
      {%- if svc_type == 'NodePort' -%}
        {{ (node_port_services.results | selectattr('vm.name', '==', vm.name) | first)['resources'][0]['spec']['ports'][0]['nodePort'] }}
      {%- endif -%}
  ansible.builtin.set_fact:
    # Here, the task is updating the `molecule_systems` dictionary with new VM information.
    # If `molecule_systems` doesn't exist, it is created as an empty dictionary.
    # Then it is combined with a new dictionary for the current VM, containing ansible connection details.
    molecule_systems: >-
      {{
        molecule_systems | default({}) | combine({
          vm.name: {
            'ansible_user': 'cloud-user',
            'ansible_host': vm.ssh_service.nodeport_host,
            'ansible_ssh_port': ssh_service_address,
            'ansible_ssh_private_key_file': tempoary_ssh_key_path
          }
        })
      }}
