blank_issues_enabled: false
contact_links:
  - name: Ask a question on the Ansible Forum
    url: https://forum.ansible.com/tags/c/project/7/molecule
    about: Recommended place for questions, debates, consultation, and new feature ideas.
  - name: Ask a question on StackOverflow
    url: https://stackoverflow.com/questions/tagged/molecule
    about: For well defined questions and answers use StackOverflow
  - name: Molecule Plugins (drivers)
    about: This includes some drivers such azure, docker, ec2, gce, podman and vagrant
    url: https://github.com/ansible-community/molecule-plugins/
