---
{% raw -%}
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    molecule_file: "{{ lookup('env', 'MOLECULE_FILE') }}"
    molecule_yml: "{{ lookup('file', molecule_file) | from_yaml }}"
  tasks:
    - name: Destroy molecule instance(s)
      docker_container:
        name: "{{ item.name }}-{{ molecule_yml.scenario.name }}"
        state: absent
      with_items: "{{ molecule_yml.platforms }}"
{%- endraw %}
